# Installs apps using the brew (cask) ecosystem
#
# Parameters:
# - brew_app_list: The list of apps to be installed with brew
# - brew_cask_app_list: The list of apps to be installed with brew cask
---

# install apps with brew
- name: Install packages with brew
  homebrew: name='{{ item.app }}'
  with_items: brew_app_list

# install apps with brew cask
- name: Install packages with brew cask
  homebrew_cask: name='{{ item.app }}'
  with_items: brew_cask_app_list
