# Installs apps using the brew (cask) ecosystem
---

# install default apps with brew
- name: Install default packages with brew
  homebrew: name='{{ item.app }}'
  with_items: brew_app_list_default

# install apps with brew
- name: Install packages with brew
  homebrew: name='{{ item.app }}'
  with_items: brew_app_list
